# Generated by Django 5.0.2 on 2024-02-10 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('icon', models.FileField(upload_to='icons')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('interior', 'Interior'), ('exterior', 'Exterior')], max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('img', models.ImageField(upload_to='portfolios')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='portfolios')),
                ('img3', models.ImageField(blank=True, null=True, upload_to='portfolios')),
                ('img4', models.ImageField(blank=True, null=True, upload_to='portfolios')),
                ('img5', models.ImageField(blank=True, null=True, upload_to='portfolios')),
                ('img6', models.ImageField(blank=True, null=True, upload_to='portfolios')),
                ('img7', models.ImageField(blank=True, null=True, upload_to='portfolios')),
                ('img8', models.ImageField(blank=True, null=True, upload_to='portfolios')),
                ('img9', models.ImageField(blank=True, null=True, upload_to='portfolios')),
                ('img10', models.ImageField(blank=True, null=True, upload_to='portfolios')),
                ('description', models.TextField()),
                ('client', models.CharField(max_length=100)),
                ('project_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('profile', models.FileField(upload_to='profiles')),
            ],
        ),
        migrations.CreateModel(
            name='Testimony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('testimony', models.TextField()),
                ('picture', models.ImageField(blank=True, upload_to='testimonies')),
            ],
        ),
    ]
